version: "3.8"
services:
  test2.5:
    image: public.ecr.aws/lambda/ruby:2.5
    entrypoint: ./bin/_test
    volumes:
      - $PWD:/var/task
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
